/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_MainActivity */

#ifndef _Included_com_example_myapplication_MainActivity
#define _Included_com_example_myapplication_MainActivity// 如果没有定义这个宏就定义
#ifdef __cplusplus//如果是C++ 环境就全部使用C的方式
extern "C" {
#endif
#undef com_example_myapplication_MainActivity_A
#define com_example_myapplication_MainActivity_A 815L
/*
 * Class:     com_example_myapplication_MainActivity
 * Method:    getStringPwd
 * Signature: ()Ljava/lang/String; 禁止函数重载
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_MainActivity_getStringPwd
  (JNIEnv *, jobject);

#ifdef __cplusplus//如果是C++ 啥事也没做
}
#endif
#endif
